a =open('hello.txt','w')
a.write('welcome')
print(a.name)
a.close()
a =open('hello.txt','r')
text = a.read()
print(text)
a.close()
import os
os.remove("hello.txt")
os.mkdir('vishwa1')
print('cwd',os.getcwd())
os.chdir("C:/")
print('cwd',os.getcwd())
        
