$('h1').click(function(){
    console.log('heading 1 was clicked')
})

$('li').click(function(){
    console.log('any li was clicked')
})

$('h1').click(function(){
    $(this).text('I was changed')
})

$('input').eq(0).keypress(function(){
    $('h3').toggleClass('turnBlue')
})

$('input').eq(1).click(function(){
    console.log('i am submit')
    $('p').addClass('turnRed')
})

$('input').eq(0).keypress(function(event){
    console.log(event)
    console.log('i am the event generated by keypress event, check me in console')
})

$('input').eq(0).keypress(function(event){
    if (event.which === 13){
        $('h1').toggleClass('turnBlue')
    }
})

$('h1').on('dblclick',function(){
    $(this).toggleClass('turnRed');
})

$('p').on('mouseenter',function(){
    $(this).toggleClass('turnBlue');
})

$('input').eq(1).on('click',function(){
    $('.selector').fadeOut(3000);
})

$('input').eq(1).on('click',function(){
    $('.container').slideUp(3000);
    console.log('i am slide up event')
})